set_synthetic_device_state:
  name: Set the synthetic device state
  description: Sets the synthetic device state to a predefined restorable attribute value.
  fields:
    config_entry:
      name: Config Entry
      description: The configuration entry for the synthetic home instance to update.
      required: true
      selector:
        config_entry:
          integration: synthetic_home
    area_name:
      name: Area Name
      description: The area name that contains the specified device.
      required: true
      example: Family Room
      selector:
        text:
    device_name:
      name: Device name
      description: The name of the device to update.
      required: true
      example: Family Room Thermostat
      selector:
        text:
    restorable_attributes_key:
      name: Restorable Attribute Key
      description: The name of the configuration key that contains the specified device state.
      required: true
      example: cool
      selector:
        text:

clear_synthetic_device_state:
  name: Clear Synthetic Device State
  description: Reset the Synthetic Device State back to the default value.
  fields:
    config_entry:
      name: Config Entry
      description: The configuration entry for the synthetic home instance to update.
      required: true
      selector:
        config_entry:
          integration: synthetic_home
