---
name: Lint

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Validate Renovate configuration
        run: |
          npx --package=renovate@38 -- renovate-config-validator .github/renovate.json5
      - uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0
      - uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2
        with:
          check_hidden: false
          ignore_words_list: hass
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
          cache-dependency-glob: "requirements_dev.txt"
          activate-environment: true
      - name: Install dependencies
        env:
          PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1
        run: |
          uv pip install -r requirements_dev.txt --prerelease=allow

      - name: Run Ruff Check
        run: |
          ruff check --output-format=github .

      - name: Run Ruff Format
        run: |
          ruff format .

      - name: Static typing with ty
        run: |
          ty check . --ignore unresolved-import
