name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main


env:
  DEFAULT_PYTHON: 3.12

jobs:
  hassfest:
    runs-on: ubuntu-latest
    name: Hassfest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Hassfest validation
      uses: home-assistant/actions/hassfest@master

  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
    - name: Check out code from GitHub
      uses: actions/checkout@v3
    - name: Setup Python ${{ env.DEFAULT_PYTHON }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.DEFAULT_PYTHON }}
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Tests suite
      run: |
        pytest
